import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

// Regenerates the SDK's offline layer from the canonical sources:
//   - sdk/src/vendor/   <- verbatim copies of the pure-logic modules
//   - sdk/src/snapshot.json <- the current dataset
// The published SDK must be self-contained (zero deps, no reach into ../src),
// but hand-copying invites drift — so copying is scripted and the copies are
// marked generated. Run after build:data; commit the results.

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const VENDOR_FILES = ['parse.ts', 'classify.ts', 'check.ts', 'mx.ts'] as const

const vendorDir = join(ROOT, 'sdk', 'src', 'vendor')
mkdirSync(vendorDir, { recursive: true })
for (const file of VENDOR_FILES) {
  const source = readFileSync(join(ROOT, 'src', 'lib', file), 'utf8')
  const header = `// GENERATED by pipeline/build-snapshot.ts — vendored copy of src/lib/${file}.\n// Do not edit here; edit the original and run "npm run build:snapshot".\n`
  writeFileSync(join(vendorDir, file), header + source)
}

const dataset = readFileSync(join(ROOT, 'data', 'dataset.json'), 'utf8')
writeFileSync(join(ROOT, 'sdk', 'src', 'snapshot.json'), dataset)

const parsed = JSON.parse(dataset) as { version: string; disposable: string[]; free_providers: string[] }
console.log(
  `SDK snapshot v${parsed.version}: ${parsed.disposable.length} disposable, ` +
  `${parsed.free_providers.length} free-provider domains; vendored ${VENDOR_FILES.length} modules`
)
